# development:
#   adapter: postgresql
#   database: db/development.db

# test:
#   adapter: postgresql
#   database: db/test.db

# fixed:
#   adapter: postgresql
#   database: db/fixed.db

development:
  adapter: postgresql
  database: db/development
  
test:
  adapter: postgresql
  database: db/test

production:
  adapter: postgresql
  database: db/production